# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8172311410c0bc1d6be054f79412f6846c6e94ee4d4156c99bc75539f4f0a46382af14795c8e66f8d46f0a80283196b6ae2934bbe2e541c826a8bea784ed3350

test:
  secret_key_base: b00457911c09423fb05cf92a0bc6dc7cfb5bf83e663e53b67440bf41cb2813bae32780801a68b85e130c84b970916306f25f768839afe1c4db602c7a1aa71b2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
